
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hasintha
 */
public class dashbord extends javax.swing.JFrame {

    /**
     * Creates new form dashbord
     */
    public dashbord() {
        initComponents();
        this.setLocationRelativeTo(null);
    }  

    String username = "";

    public void getuser(String user) {
        username = user;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inventoryBtn = new javax.swing.JButton();
        accountsBtn = new javax.swing.JButton();
        billingBtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        settingsBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        toolsBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        countLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        digitalClock1 = new digitalclock.DigitalClock();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shop Dashboard");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel1KeyReleased(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(42, 108, 171));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MY POS DASHBOARD");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 410, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop-icon (1)75.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 140, 110));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Write Your Success Story Today ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 130));

        inventoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventory.png"))); // NOI18N
        inventoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inventoryBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                inventoryBtnMouseReleased(evt);
            }
        });
        inventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryBtnActionPerformed(evt);
            }
        });
        jPanel1.add(inventoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 170, 100));

        accountsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accounts.png"))); // NOI18N
        accountsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accountsBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                accountsBtnMouseReleased(evt);
            }
        });
        jPanel1.add(accountsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 170, 100));

        billingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Billing.png"))); // NOI18N
        billingBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                billingBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                billingBtnMouseReleased(evt);
            }
        });
        billingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingBtnActionPerformed(evt);
            }
        });
        jPanel1.add(billingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 170, 100));

        aboutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about.png"))); // NOI18N
        aboutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aboutBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                aboutBtnMouseReleased(evt);
            }
        });
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(aboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 170, 100));

        settingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/setting.png"))); // NOI18N
        settingsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                settingsBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                settingsBtnMouseReleased(evt);
            }
        });
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(settingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 170, 100));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 970, 10));

        toolsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tools.png"))); // NOI18N
        toolsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toolsBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                toolsBtnMouseReleased(evt);
            }
        });
        jPanel1.add(toolsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 170, 100));

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("License :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        countLbl.setForeground(new java.awt.Color(255, 51, 51));
        countLbl.setText("05");
        jPanel1.add(countLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 30, -1));

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Days Remaining");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, -1, -1));

        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Copyright ©  |   The Compilers  2018");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, -1, -1));
        jPanel1.add(digitalClock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dash_box.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 350, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Button Icon Changes
    private void billingBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billingBtnMousePressed
        // TODO add your handling code here:
        billingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Billing clicked.png"))); // NOI18N
    }//GEN-LAST:event_billingBtnMousePressed

    private void billingBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billingBtnMouseReleased
        // TODO add your handling code here:
        billingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Billing.png"))); // NOI18N
    }//GEN-LAST:event_billingBtnMouseReleased

    private void accountsBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsBtnMouseReleased
        // TODO add your handling code here:
        accountsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accounts.png"))); // NOI18N
    }//GEN-LAST:event_accountsBtnMouseReleased

    private void accountsBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsBtnMousePressed
        // TODO add your handling code here:
        accountsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accounts_clicked.png"))); // NOI18N
    }//GEN-LAST:event_accountsBtnMousePressed

    private void inventoryBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryBtnMousePressed
        // TODO add your handling code here:
        inventoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventory_clicked.png"))); // NOI18N
    }//GEN-LAST:event_inventoryBtnMousePressed

    private void inventoryBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryBtnMouseReleased
        // TODO add your handling code here:
        inventoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventory.png"))); // NOI18N
    }//GEN-LAST:event_inventoryBtnMouseReleased

    private void settingsBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseReleased
        // TODO add your handling code here:
        settingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/setting.png"))); // NOI18N

    }//GEN-LAST:event_settingsBtnMouseReleased

    private void settingsBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMousePressed
        // TODO add your handling code here:
        settingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/setting_clicked.png")));
    }//GEN-LAST:event_settingsBtnMousePressed

    private void aboutBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutBtnMousePressed
        // TODO add your handling code here:
        aboutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about_clicked.png"))); // NOI18N
    }//GEN-LAST:event_aboutBtnMousePressed

    private void aboutBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutBtnMouseReleased
        // TODO add your handling code here:
        aboutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about.png"))); // NOI18N
    }//GEN-LAST:event_aboutBtnMouseReleased

    private void toolsBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolsBtnMouseReleased
        // TODO add your handling code here:
        toolsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tools.png"))); // NOI18N
    }//GEN-LAST:event_toolsBtnMouseReleased

    private void toolsBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolsBtnMousePressed
        // TODO add your handling code here:
        toolsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tools_clicked.png"))); // NOI18N
    }//GEN-LAST:event_toolsBtnMousePressed

    private void billingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingBtnActionPerformed
        // TODO add your handling code here:
        invoice inv = new invoice();
        inv.setVisible(true);

    }//GEN-LAST:event_billingBtnActionPerformed

    private void inventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryBtnActionPerformed
        // TODO add your handling code here:
        inventory inv = new inventory();
        inv.setVisible(true);

    }//GEN-LAST:event_inventoryBtnActionPerformed

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        // TODO add your handling code here:
        settings s = new settings();
        s.setVisible(true);
        s.getuser(username);
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        // TODO add your handling code here:
        info in = new info();
        in.setVisible(true);
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void jPanel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyReleased
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jPanel1KeyReleased

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        System.err.println("");
    }//GEN-LAST:event_formKeyReleased
// End of Button Icon Changes

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashbord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn;
    private javax.swing.JButton accountsBtn;
    private javax.swing.JButton billingBtn;
    private javax.swing.JLabel countLbl;
    private digitalclock.DigitalClock digitalClock1;
    private javax.swing.JButton inventoryBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton settingsBtn;
    private javax.swing.JButton toolsBtn;
    // End of variables declaration//GEN-END:variables


}
