
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hasintha
 */
public class Inserting_Barcode extends javax.swing.JFrame {
   
    /**
     * Creates new form Inserting_Barcode
     */
    public Inserting_Barcode() {
        initComponents();
         jLblset.setText("");
         jLblset1.setText("");
         this.setLocationRelativeTo(null);
    }
      public void search(){ 
        try{
            Connect con=new Connect();
            String query="select name from item where id like '"+jtxtID.getText()+"'"; 
         
            ResultSet rs=con.getQuery(query);
            if(rs.next()){
            
            String name=rs.getString("name");
            jtxtSNAME.setText(name);
             jtxtBarcode.requestFocus();
            }
            
            rs.close(); 
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            jLblset1.setText("Item Id Was Not Found!");
        }
        
    }
      
      public void inserting(){
         
          try{
              Connect con=new Connect();
              String query="insert into barcode (barcode,item_id) values('"+jtxtBarcode.getText()+"','"+jtxtID.getText()+"')";
              int genId=con.setQuery(query,"");
              
          }catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
          }
          
          
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtxtID = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtxtSNAME = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtxtBarcode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLblset = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLblset1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Inserting_Barcodes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 33));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 64));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtIDKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 130, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Item Id: ");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Item Name: ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 40));

        jtxtSNAME.setEditable(false);
        jtxtSNAME.setBackground(new java.awt.Color(255, 255, 255));
        jtxtSNAME.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jtxtSNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtSNAMEKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtSNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 160, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Barcode:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 40));

        jtxtBarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBarcodeKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 160, 30));

        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        jLblset.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLblset.setForeground(new java.awt.Color(51, 255, 51));
        jLblset.setText("Barcode Added Successfully!");
        jPanel2.add(jLblset, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 200, -1));

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        jLblset1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLblset1.setForeground(new java.awt.Color(255, 51, 51));
        jLblset1.setText("Item Id Was Not Found!");
        jPanel2.add(jLblset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 200, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 510, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtIDKeyReleased
    if(evt.getKeyCode()==KeyEvent.VK_ENTER){
         jtxtSNAME.setText("");
            search();
           
        }
    }//GEN-LAST:event_jtxtIDKeyReleased

    private void jtxtSNAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSNAMEKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSNAMEKeyReleased

    private void jtxtBarcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBarcodeKeyReleased
       if(!jtxtSNAME.getText().equals("")){
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jLblset1.setText("");
            inserting();
            jLblset.setText("");
            jtxtBarcode.setText("");
            jLblset.setText("Barcode Added Successfully!");
            jtxtBarcode.requestFocus();
        }
         
       }else{
           jLblset1.setText("Item Id Was Not Found!");
       }
    }//GEN-LAST:event_jtxtBarcodeKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jtxtSNAME.setText("");
        search();
   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtIDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIDKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inserting_Barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inserting_Barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inserting_Barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inserting_Barcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inserting_Barcode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLblset;
    private javax.swing.JLabel jLblset1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jtxtBarcode;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtSNAME;
    // End of variables declaration//GEN-END:variables
}
